package com.komlin.modular.user.model;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_c_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Integer uiCId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_r_id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Integer uiRId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_account
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_name
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_sex
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Integer uiSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_password
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_phoneNum
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiPhonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_createTime
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Date uiCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_nick
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_head_pic
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiHeadPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_ry_token
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiRyToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_rytoken_time
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Date uiRytokenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_status
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private Byte uiStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ui_salt
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    private String uiSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_Id
     *
     * @return the value of user_info.ui_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiId() {
        return uiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_Id
     *
     * @param uiId the value for user_info.ui_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiId(String uiId) {
        this.uiId = uiId == null ? null : uiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_c_Id
     *
     * @return the value of user_info.ui_c_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Integer getUiCId() {
        return uiCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_c_Id
     *
     * @param uiCId the value for user_info.ui_c_Id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiCId(Integer uiCId) {
        this.uiCId = uiCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_r_id
     *
     * @return the value of user_info.ui_r_id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Integer getUiRId() {
        return uiRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_r_id
     *
     * @param uiRId the value for user_info.ui_r_id
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiRId(Integer uiRId) {
        this.uiRId = uiRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_account
     *
     * @return the value of user_info.ui_account
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiAccount() {
        return uiAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_account
     *
     * @param uiAccount the value for user_info.ui_account
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiAccount(String uiAccount) {
        this.uiAccount = uiAccount == null ? null : uiAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_name
     *
     * @return the value of user_info.ui_name
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiName() {
        return uiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_name
     *
     * @param uiName the value for user_info.ui_name
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiName(String uiName) {
        this.uiName = uiName == null ? null : uiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_sex
     *
     * @return the value of user_info.ui_sex
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Integer getUiSex() {
        return uiSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_sex
     *
     * @param uiSex the value for user_info.ui_sex
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiSex(Integer uiSex) {
        this.uiSex = uiSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_password
     *
     * @return the value of user_info.ui_password
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiPassword() {
        return uiPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_password
     *
     * @param uiPassword the value for user_info.ui_password
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiPassword(String uiPassword) {
        this.uiPassword = uiPassword == null ? null : uiPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_phoneNum
     *
     * @return the value of user_info.ui_phoneNum
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiPhonenum() {
        return uiPhonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_phoneNum
     *
     * @param uiPhonenum the value for user_info.ui_phoneNum
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiPhonenum(String uiPhonenum) {
        this.uiPhonenum = uiPhonenum == null ? null : uiPhonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_createTime
     *
     * @return the value of user_info.ui_createTime
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Date getUiCreatetime() {
        return uiCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_createTime
     *
     * @param uiCreatetime the value for user_info.ui_createTime
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiCreatetime(Date uiCreatetime) {
        this.uiCreatetime = uiCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_nick
     *
     * @return the value of user_info.ui_nick
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiNick() {
        return uiNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_nick
     *
     * @param uiNick the value for user_info.ui_nick
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiNick(String uiNick) {
        this.uiNick = uiNick == null ? null : uiNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_head_pic
     *
     * @return the value of user_info.ui_head_pic
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiHeadPic() {
        return uiHeadPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_head_pic
     *
     * @param uiHeadPic the value for user_info.ui_head_pic
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiHeadPic(String uiHeadPic) {
        this.uiHeadPic = uiHeadPic == null ? null : uiHeadPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_ry_token
     *
     * @return the value of user_info.ui_ry_token
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiRyToken() {
        return uiRyToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_ry_token
     *
     * @param uiRyToken the value for user_info.ui_ry_token
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiRyToken(String uiRyToken) {
        this.uiRyToken = uiRyToken == null ? null : uiRyToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_rytoken_time
     *
     * @return the value of user_info.ui_rytoken_time
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Date getUiRytokenTime() {
        return uiRytokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_rytoken_time
     *
     * @param uiRytokenTime the value for user_info.ui_rytoken_time
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiRytokenTime(Date uiRytokenTime) {
        this.uiRytokenTime = uiRytokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_status
     *
     * @return the value of user_info.ui_status
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Byte getUiStatus() {
        return uiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_status
     *
     * @param uiStatus the value for user_info.ui_status
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiStatus(Byte uiStatus) {
        this.uiStatus = uiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ui_salt
     *
     * @return the value of user_info.ui_salt
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getUiSalt() {
        return uiSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ui_salt
     *
     * @param uiSalt the value for user_info.ui_salt
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setUiSalt(String uiSalt) {
        this.uiSalt = uiSalt == null ? null : uiSalt.trim();
    }
}