package com.komlin.modular.user.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUiIdIsNull() {
            addCriterion("ui_Id is null");
            return (Criteria) this;
        }

        public Criteria andUiIdIsNotNull() {
            addCriterion("ui_Id is not null");
            return (Criteria) this;
        }

        public Criteria andUiIdEqualTo(String value) {
            addCriterion("ui_Id =", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdNotEqualTo(String value) {
            addCriterion("ui_Id <>", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdGreaterThan(String value) {
            addCriterion("ui_Id >", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdGreaterThanOrEqualTo(String value) {
            addCriterion("ui_Id >=", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdLessThan(String value) {
            addCriterion("ui_Id <", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdLessThanOrEqualTo(String value) {
            addCriterion("ui_Id <=", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdLike(String value) {
            addCriterion("ui_Id like", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdNotLike(String value) {
            addCriterion("ui_Id not like", value, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdIn(List<String> values) {
            addCriterion("ui_Id in", values, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdNotIn(List<String> values) {
            addCriterion("ui_Id not in", values, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdBetween(String value1, String value2) {
            addCriterion("ui_Id between", value1, value2, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiIdNotBetween(String value1, String value2) {
            addCriterion("ui_Id not between", value1, value2, "uiId");
            return (Criteria) this;
        }

        public Criteria andUiCIdIsNull() {
            addCriterion("ui_c_Id is null");
            return (Criteria) this;
        }

        public Criteria andUiCIdIsNotNull() {
            addCriterion("ui_c_Id is not null");
            return (Criteria) this;
        }

        public Criteria andUiCIdEqualTo(Integer value) {
            addCriterion("ui_c_Id =", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdNotEqualTo(Integer value) {
            addCriterion("ui_c_Id <>", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdGreaterThan(Integer value) {
            addCriterion("ui_c_Id >", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ui_c_Id >=", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdLessThan(Integer value) {
            addCriterion("ui_c_Id <", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdLessThanOrEqualTo(Integer value) {
            addCriterion("ui_c_Id <=", value, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdIn(List<Integer> values) {
            addCriterion("ui_c_Id in", values, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdNotIn(List<Integer> values) {
            addCriterion("ui_c_Id not in", values, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdBetween(Integer value1, Integer value2) {
            addCriterion("ui_c_Id between", value1, value2, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiCIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ui_c_Id not between", value1, value2, "uiCId");
            return (Criteria) this;
        }

        public Criteria andUiRIdIsNull() {
            addCriterion("ui_r_id is null");
            return (Criteria) this;
        }

        public Criteria andUiRIdIsNotNull() {
            addCriterion("ui_r_id is not null");
            return (Criteria) this;
        }

        public Criteria andUiRIdEqualTo(Integer value) {
            addCriterion("ui_r_id =", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdNotEqualTo(Integer value) {
            addCriterion("ui_r_id <>", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdGreaterThan(Integer value) {
            addCriterion("ui_r_id >", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ui_r_id >=", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdLessThan(Integer value) {
            addCriterion("ui_r_id <", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdLessThanOrEqualTo(Integer value) {
            addCriterion("ui_r_id <=", value, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdIn(List<Integer> values) {
            addCriterion("ui_r_id in", values, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdNotIn(List<Integer> values) {
            addCriterion("ui_r_id not in", values, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdBetween(Integer value1, Integer value2) {
            addCriterion("ui_r_id between", value1, value2, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiRIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ui_r_id not between", value1, value2, "uiRId");
            return (Criteria) this;
        }

        public Criteria andUiAccountIsNull() {
            addCriterion("ui_account is null");
            return (Criteria) this;
        }

        public Criteria andUiAccountIsNotNull() {
            addCriterion("ui_account is not null");
            return (Criteria) this;
        }

        public Criteria andUiAccountEqualTo(String value) {
            addCriterion("ui_account =", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountNotEqualTo(String value) {
            addCriterion("ui_account <>", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountGreaterThan(String value) {
            addCriterion("ui_account >", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountGreaterThanOrEqualTo(String value) {
            addCriterion("ui_account >=", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountLessThan(String value) {
            addCriterion("ui_account <", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountLessThanOrEqualTo(String value) {
            addCriterion("ui_account <=", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountLike(String value) {
            addCriterion("ui_account like", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountNotLike(String value) {
            addCriterion("ui_account not like", value, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountIn(List<String> values) {
            addCriterion("ui_account in", values, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountNotIn(List<String> values) {
            addCriterion("ui_account not in", values, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountBetween(String value1, String value2) {
            addCriterion("ui_account between", value1, value2, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiAccountNotBetween(String value1, String value2) {
            addCriterion("ui_account not between", value1, value2, "uiAccount");
            return (Criteria) this;
        }

        public Criteria andUiNameIsNull() {
            addCriterion("ui_name is null");
            return (Criteria) this;
        }

        public Criteria andUiNameIsNotNull() {
            addCriterion("ui_name is not null");
            return (Criteria) this;
        }

        public Criteria andUiNameEqualTo(String value) {
            addCriterion("ui_name =", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameNotEqualTo(String value) {
            addCriterion("ui_name <>", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameGreaterThan(String value) {
            addCriterion("ui_name >", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameGreaterThanOrEqualTo(String value) {
            addCriterion("ui_name >=", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameLessThan(String value) {
            addCriterion("ui_name <", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameLessThanOrEqualTo(String value) {
            addCriterion("ui_name <=", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameLike(String value) {
            addCriterion("ui_name like", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameNotLike(String value) {
            addCriterion("ui_name not like", value, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameIn(List<String> values) {
            addCriterion("ui_name in", values, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameNotIn(List<String> values) {
            addCriterion("ui_name not in", values, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameBetween(String value1, String value2) {
            addCriterion("ui_name between", value1, value2, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiNameNotBetween(String value1, String value2) {
            addCriterion("ui_name not between", value1, value2, "uiName");
            return (Criteria) this;
        }

        public Criteria andUiSexIsNull() {
            addCriterion("ui_sex is null");
            return (Criteria) this;
        }

        public Criteria andUiSexIsNotNull() {
            addCriterion("ui_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUiSexEqualTo(Integer value) {
            addCriterion("ui_sex =", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexNotEqualTo(Integer value) {
            addCriterion("ui_sex <>", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexGreaterThan(Integer value) {
            addCriterion("ui_sex >", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("ui_sex >=", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexLessThan(Integer value) {
            addCriterion("ui_sex <", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexLessThanOrEqualTo(Integer value) {
            addCriterion("ui_sex <=", value, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexIn(List<Integer> values) {
            addCriterion("ui_sex in", values, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexNotIn(List<Integer> values) {
            addCriterion("ui_sex not in", values, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexBetween(Integer value1, Integer value2) {
            addCriterion("ui_sex between", value1, value2, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiSexNotBetween(Integer value1, Integer value2) {
            addCriterion("ui_sex not between", value1, value2, "uiSex");
            return (Criteria) this;
        }

        public Criteria andUiPasswordIsNull() {
            addCriterion("ui_password is null");
            return (Criteria) this;
        }

        public Criteria andUiPasswordIsNotNull() {
            addCriterion("ui_password is not null");
            return (Criteria) this;
        }

        public Criteria andUiPasswordEqualTo(String value) {
            addCriterion("ui_password =", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordNotEqualTo(String value) {
            addCriterion("ui_password <>", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordGreaterThan(String value) {
            addCriterion("ui_password >", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("ui_password >=", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordLessThan(String value) {
            addCriterion("ui_password <", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordLessThanOrEqualTo(String value) {
            addCriterion("ui_password <=", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordLike(String value) {
            addCriterion("ui_password like", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordNotLike(String value) {
            addCriterion("ui_password not like", value, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordIn(List<String> values) {
            addCriterion("ui_password in", values, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordNotIn(List<String> values) {
            addCriterion("ui_password not in", values, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordBetween(String value1, String value2) {
            addCriterion("ui_password between", value1, value2, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPasswordNotBetween(String value1, String value2) {
            addCriterion("ui_password not between", value1, value2, "uiPassword");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumIsNull() {
            addCriterion("ui_phoneNum is null");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumIsNotNull() {
            addCriterion("ui_phoneNum is not null");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumEqualTo(String value) {
            addCriterion("ui_phoneNum =", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumNotEqualTo(String value) {
            addCriterion("ui_phoneNum <>", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumGreaterThan(String value) {
            addCriterion("ui_phoneNum >", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumGreaterThanOrEqualTo(String value) {
            addCriterion("ui_phoneNum >=", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumLessThan(String value) {
            addCriterion("ui_phoneNum <", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumLessThanOrEqualTo(String value) {
            addCriterion("ui_phoneNum <=", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumLike(String value) {
            addCriterion("ui_phoneNum like", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumNotLike(String value) {
            addCriterion("ui_phoneNum not like", value, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumIn(List<String> values) {
            addCriterion("ui_phoneNum in", values, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumNotIn(List<String> values) {
            addCriterion("ui_phoneNum not in", values, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumBetween(String value1, String value2) {
            addCriterion("ui_phoneNum between", value1, value2, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiPhonenumNotBetween(String value1, String value2) {
            addCriterion("ui_phoneNum not between", value1, value2, "uiPhonenum");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeIsNull() {
            addCriterion("ui_createTime is null");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeIsNotNull() {
            addCriterion("ui_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeEqualTo(Date value) {
            addCriterion("ui_createTime =", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeNotEqualTo(Date value) {
            addCriterion("ui_createTime <>", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeGreaterThan(Date value) {
            addCriterion("ui_createTime >", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ui_createTime >=", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeLessThan(Date value) {
            addCriterion("ui_createTime <", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("ui_createTime <=", value, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeIn(List<Date> values) {
            addCriterion("ui_createTime in", values, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeNotIn(List<Date> values) {
            addCriterion("ui_createTime not in", values, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeBetween(Date value1, Date value2) {
            addCriterion("ui_createTime between", value1, value2, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("ui_createTime not between", value1, value2, "uiCreatetime");
            return (Criteria) this;
        }

        public Criteria andUiNickIsNull() {
            addCriterion("ui_nick is null");
            return (Criteria) this;
        }

        public Criteria andUiNickIsNotNull() {
            addCriterion("ui_nick is not null");
            return (Criteria) this;
        }

        public Criteria andUiNickEqualTo(String value) {
            addCriterion("ui_nick =", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickNotEqualTo(String value) {
            addCriterion("ui_nick <>", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickGreaterThan(String value) {
            addCriterion("ui_nick >", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickGreaterThanOrEqualTo(String value) {
            addCriterion("ui_nick >=", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickLessThan(String value) {
            addCriterion("ui_nick <", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickLessThanOrEqualTo(String value) {
            addCriterion("ui_nick <=", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickLike(String value) {
            addCriterion("ui_nick like", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickNotLike(String value) {
            addCriterion("ui_nick not like", value, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickIn(List<String> values) {
            addCriterion("ui_nick in", values, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickNotIn(List<String> values) {
            addCriterion("ui_nick not in", values, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickBetween(String value1, String value2) {
            addCriterion("ui_nick between", value1, value2, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiNickNotBetween(String value1, String value2) {
            addCriterion("ui_nick not between", value1, value2, "uiNick");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicIsNull() {
            addCriterion("ui_head_pic is null");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicIsNotNull() {
            addCriterion("ui_head_pic is not null");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicEqualTo(String value) {
            addCriterion("ui_head_pic =", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicNotEqualTo(String value) {
            addCriterion("ui_head_pic <>", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicGreaterThan(String value) {
            addCriterion("ui_head_pic >", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicGreaterThanOrEqualTo(String value) {
            addCriterion("ui_head_pic >=", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicLessThan(String value) {
            addCriterion("ui_head_pic <", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicLessThanOrEqualTo(String value) {
            addCriterion("ui_head_pic <=", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicLike(String value) {
            addCriterion("ui_head_pic like", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicNotLike(String value) {
            addCriterion("ui_head_pic not like", value, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicIn(List<String> values) {
            addCriterion("ui_head_pic in", values, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicNotIn(List<String> values) {
            addCriterion("ui_head_pic not in", values, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicBetween(String value1, String value2) {
            addCriterion("ui_head_pic between", value1, value2, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiHeadPicNotBetween(String value1, String value2) {
            addCriterion("ui_head_pic not between", value1, value2, "uiHeadPic");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenIsNull() {
            addCriterion("ui_ry_token is null");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenIsNotNull() {
            addCriterion("ui_ry_token is not null");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenEqualTo(String value) {
            addCriterion("ui_ry_token =", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenNotEqualTo(String value) {
            addCriterion("ui_ry_token <>", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenGreaterThan(String value) {
            addCriterion("ui_ry_token >", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenGreaterThanOrEqualTo(String value) {
            addCriterion("ui_ry_token >=", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenLessThan(String value) {
            addCriterion("ui_ry_token <", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenLessThanOrEqualTo(String value) {
            addCriterion("ui_ry_token <=", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenLike(String value) {
            addCriterion("ui_ry_token like", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenNotLike(String value) {
            addCriterion("ui_ry_token not like", value, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenIn(List<String> values) {
            addCriterion("ui_ry_token in", values, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenNotIn(List<String> values) {
            addCriterion("ui_ry_token not in", values, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenBetween(String value1, String value2) {
            addCriterion("ui_ry_token between", value1, value2, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRyTokenNotBetween(String value1, String value2) {
            addCriterion("ui_ry_token not between", value1, value2, "uiRyToken");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeIsNull() {
            addCriterion("ui_rytoken_time is null");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeIsNotNull() {
            addCriterion("ui_rytoken_time is not null");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeEqualTo(Date value) {
            addCriterion("ui_rytoken_time =", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeNotEqualTo(Date value) {
            addCriterion("ui_rytoken_time <>", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeGreaterThan(Date value) {
            addCriterion("ui_rytoken_time >", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ui_rytoken_time >=", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeLessThan(Date value) {
            addCriterion("ui_rytoken_time <", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeLessThanOrEqualTo(Date value) {
            addCriterion("ui_rytoken_time <=", value, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeIn(List<Date> values) {
            addCriterion("ui_rytoken_time in", values, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeNotIn(List<Date> values) {
            addCriterion("ui_rytoken_time not in", values, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeBetween(Date value1, Date value2) {
            addCriterion("ui_rytoken_time between", value1, value2, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiRytokenTimeNotBetween(Date value1, Date value2) {
            addCriterion("ui_rytoken_time not between", value1, value2, "uiRytokenTime");
            return (Criteria) this;
        }

        public Criteria andUiStatusIsNull() {
            addCriterion("ui_status is null");
            return (Criteria) this;
        }

        public Criteria andUiStatusIsNotNull() {
            addCriterion("ui_status is not null");
            return (Criteria) this;
        }

        public Criteria andUiStatusEqualTo(Byte value) {
            addCriterion("ui_status =", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusNotEqualTo(Byte value) {
            addCriterion("ui_status <>", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusGreaterThan(Byte value) {
            addCriterion("ui_status >", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("ui_status >=", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusLessThan(Byte value) {
            addCriterion("ui_status <", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusLessThanOrEqualTo(Byte value) {
            addCriterion("ui_status <=", value, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusIn(List<Byte> values) {
            addCriterion("ui_status in", values, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusNotIn(List<Byte> values) {
            addCriterion("ui_status not in", values, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusBetween(Byte value1, Byte value2) {
            addCriterion("ui_status between", value1, value2, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("ui_status not between", value1, value2, "uiStatus");
            return (Criteria) this;
        }

        public Criteria andUiSaltIsNull() {
            addCriterion("ui_salt is null");
            return (Criteria) this;
        }

        public Criteria andUiSaltIsNotNull() {
            addCriterion("ui_salt is not null");
            return (Criteria) this;
        }

        public Criteria andUiSaltEqualTo(String value) {
            addCriterion("ui_salt =", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltNotEqualTo(String value) {
            addCriterion("ui_salt <>", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltGreaterThan(String value) {
            addCriterion("ui_salt >", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltGreaterThanOrEqualTo(String value) {
            addCriterion("ui_salt >=", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltLessThan(String value) {
            addCriterion("ui_salt <", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltLessThanOrEqualTo(String value) {
            addCriterion("ui_salt <=", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltLike(String value) {
            addCriterion("ui_salt like", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltNotLike(String value) {
            addCriterion("ui_salt not like", value, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltIn(List<String> values) {
            addCriterion("ui_salt in", values, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltNotIn(List<String> values) {
            addCriterion("ui_salt not in", values, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltBetween(String value1, String value2) {
            addCriterion("ui_salt between", value1, value2, "uiSalt");
            return (Criteria) this;
        }

        public Criteria andUiSaltNotBetween(String value1, String value2) {
            addCriterion("ui_salt not between", value1, value2, "uiSalt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated do_not_delete_during_merge Fri May 18 16:30:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Fri May 18 16:30:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}